name: pont
description: pont
publish_to: none

version: 1.0.5+6

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_nfc_kit: ^3.3.1
  intl: ^0.17.0
  path_provider: ^2.0.11
  get_it: ^7.2.0
  package_info_plus: ^1.4.2
  flutter_bloc: ^8.0.1
  built_value: ^8.3.3
  share_plus: ^4.0.10
  dio: ^4.0.6
  rxdart: ^0.27.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.0
  shelf: ^1.3.1
  url_launcher: ^6.1.4
  firebase_dynamic_links: ^4.3.1
  firebase_core: ^1.19.1
  uuid: ^3.0.6
  cloud_firestore: ^3.2.1
  shared_preferences: ^2.0.15
  flutter_svg: ^1.0.3
  modal_bottom_sheet: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.11
  built_value_generator: ^8.3.3
  flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/