// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxoO19d-PB9O4IKpdIsL9NdYWyxOhDK9E',
    appId: '1:1074512840342:android:44141d43005480006824b7',
    messagingSenderId: '1074512840342',
    projectId: 'pont-68d4e',
    storageBucket: 'pont-68d4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI6fA3ujbgINBC0_-DXnyFRSTJj2y0F6U',
    appId: '1:1074512840342:ios:0e1645529df8a95b6824b7',
    messagingSenderId: '1074512840342',
    projectId: 'pont-68d4e',
    storageBucket: 'pont-68d4e.appspot.com',
    androidClientId: '1074512840342-8ov1b554lb4un2iiv3cn69m107iqf1no.apps.googleusercontent.com',
    iosClientId: '1074512840342-q9vf2queqcgudkcf8lvgqpsgb9662s0j.apps.googleusercontent.com',
    iosBundleId: 'dev.optimist.pont',
  );
}
